const Styles = {
  home: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000033",
    userSelect: "none",
    overflow: "hidden",
  },
  backParent: {
    backgroundColor: "rgba(255,255,255,0.7)",
    width: "320px",
    borderRadius: "20px",
    height: "40px",
    position: "absolute",
    right: "60px",
    top: "10px",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.5)",
    },
  },
  back: {
    gap: "10px",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    userSelect: "none",
    fontSize: "1rem",
  },
  menuIcon: {
    position: "absolute",
    right: "10px",
    color: "#000",
    top: "11px",
    borderRadius: "5px",
    fontSize: "1.5rem",
    padding: "7px 7px 4px 7px",
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  backText: {
    fontFamily: "'Belanosima', sans-serif;",
    fontSize: "1rem",
  },
  customInputButton: {
    cursor: "pointer",
    width: "100%",
    height: "100%",
    gap: "5px",
    fontSize: "1.2rem",
    display: "flex",
    borderRadius: "20px",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.5)",
    },
  },
  taskbar: {
    height: "25px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.5)",
    width: "10%",
    fontSize: "1.2rem",
    position: "absolute",
    bottom: "0px",
    left: "45%",
    borderRadius: "5px 5px 0px 0px",
  },
};

export default Styles;
