const Styles = {
  "@keyframes bringTop": {
    from: {
      width: "90%",
      height: "80px",
    },
    to: {
      width: "0",
      height: "0px",
    },
  },
  "@keyframes goDown": {
    from: {
      height: "35px",
      padding: "10px 0",
    },
    to: {
      height: "0px",
      padding: 0,
    },
  },
  home: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    backgroundColor: "#013243",
    userSelect: "none",
    overflow: "hidden",
  },
  backParent: {
    backgroundColor: "rgba(0,0,0,0.5)",
    width: "320px",
    borderRadius: "20px",
    height: "40px",
    position: "absolute",
    right: "60px",
    top: "10px",
    color: "white",
    "&:hover": {
      backgroundColor: "rgba(0,0,0,0.8)",
    },
  },
  back: {
    gap: "10px",
    justifyContent: "center",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    userSelect: "none",
    fontSize: "1rem",
  },
  menuIcon: {
    position: "absolute",
    right: "10px",
    top: "11px",
    borderRadius: "5px",
    fontSize: "1.5rem",
    color: "white",
    padding: "7px 7px 4px 7px",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  backText: {
    fontFamily: "'Belanosima', sans-serif;",
    fontSize: "1rem",
  },
  customInputButton: {
    cursor: "pointer",
    width: "100%",
    height: "100%",
    gap: "5px",
    fontSize: "1.2rem",
    display: "flex",
    borderRadius: "20px",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "800",
    "&:hover": {
      backgroundColor: "rgba(0,0,0,0.7)",
    },
  },
  icon: {
    padding: "10px 5px 5px 5px",
    fontSize: "1rem",
    borderRadius: "7px 7px 0 0",
    width: "160px",
    height: "15px",
    display: "flex",
    justifyContent: "center",
    color: "white",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  taskbar: {
    width: "90%",
    position: "absolute",
    borderRadius: "10px",
    bottom: "0px",
    left: "5%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  closeBar: {
    width: "160px",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  fakeTask: {
    backgroundColor: "rgba(0,0,0,0.7)",
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "20px",
    fontSize: "25px",

    justifyContent: "center",
    color: "white",
    borderRadius: "10px 10px 0 0",
    animationName: "$goDown",
    animationDuration: "500ms",
    animationTimingFunction: "linear",
  },
};

export default Styles;
