const styles = {
  parent: {
    contentVisibility: (props) => {
      return props.state.timer[1] ? "visible" : "hidden";
    },
    visibility: (props) => {
      return props.state.timer[1] ? "visible" : "hidden";
    },
    width: "250px",
    backgroundColor: "rgba(255,255,255,0.4)",
    padding: "15px",
    position: "absolute",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    top: "10px",
    left: "10px",
    borderRadius: "10px",
    maxHeight: "90%",
    overflowY: "auto",
  },
  input: {
    width: "50px",
    height: "50px",
    border: "none",
    fontSize: "25px",
    borderRadius: "5px",
    textAlign: "center",
  },
  button: {
    border: "none",
    width: "100px",
    height: "25px",
    borderRadius: "5px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
  },

  timerInp: {
    flexDirection: "column",
    display: "flex",
    gap: "10px",
    backgroundColor: "rgba(0,0,0,0.5)",
    padding: "15px 20px",
    borderRadius: "5px",
  },
  select: {
    textAlign: "center",
    fontSize: "15px",
    width: "115px",
    fontWeight: "700",
    height: "25px",
    borderRadius: "5px",
  },
  numInp: {
    display: "flex",
    gap: "5px",
  },
  timerCurrent: {
    color: "white",
    display: "flex",
    gap: "10px",
    padding: "5px",
    width: "90%",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: "5px",
  },
  timerCurrentText: {
    fontWeight: "700",
    fontSize: "1.2rem",
    borderRadius: "5px",
    display: "flex",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0)",
    padding: "10px",
    width: "20px",
  },
  timers: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "10px",
    justifyContent: "center",
  },
  timerTop: {
    color: "white",
    backgroundColor: "rgba(0,0,0,0.4)",
    width: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px 0",
  },
  mini: {
    position: "absolute",
    color: "rgba(0,0,0,0.7)",
    top: "5px",
    fontSize: "1.7rem",
    right: "5px",
  },
};

export default styles;
